# Generated by Django 3.2.9 on 2021-12-12 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(default='A short description', max_length=256)),
                ('visibilty', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('source_code_url', models.URLField(blank=True, default=None, null=True)),
                ('deployment_code', models.URLField(blank=True, default=None, null=True)),
                ('developers', models.ManyToManyField(related_name='dev', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('body', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.project'),
        ),
    ]
