# Generated by Django 3.2.9 on 2021-12-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211214_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='visibilty',
            new_name='visibility',
        ),
    ]
