FROM python:3.9-slim-buster@sha256:00a0ecccb4ace2774dbf4cf5338e3568ce9dd82f7f1f8137881983342f2bdf7b

WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN pip install -r requirements.txt

COPY . .

